Update NXstress.nxdl.xml
woutdenolf/definitions pull request #8
Opened 2024-05-10 12:25 UTC by aapaecklar

Hello,

here are some suggestions for small changes and a points of thoughts:

For the energy, if it is for energy dispersive diffraction, should we allow two values and not just one float value? 

With kind regards,
Arnold

2024-05-10 15:11 UTC, woutdenolf requested changes

2024-05-10 15:11 UTC, woutdenolf commented on contributed_definitions/NXstress.nxdl.xml
> +                            - if *center_type="momentum-transfer"* then *cUnit* must have the unit \ :math:`\unicode{x212B}^{-1}`
`\unicode{x212B}` breaks the PDF building. Not sure how to solve it. At least when we provide Å, the HTML docs are ok.

2024-05-10 15:11 UTC, woutdenolf commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
"In case of energy dispersive diffraction, the lowest and highest energy should be provided."

What does this mean? ED-XRD has a monochromatic X-ray beam.

2024-05-10 15:21 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +                            - if *center_type="momentum-transfer"* then *cUnit* must have the unit \ :math:`\unicode{x212B}^{-1}`
Ok, we can go with your version. The only reason why I went with unicode is that the angstrom symbol looks nices (not italics).

2024-05-10 15:23 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
Maybe I am confused now. I thought that angular dispersive has a monochromatic beam and ED-XRD has several different wavelengths in the white beam (https://www.diamond.ac.uk/Instruments/Techniques/Diffraction/EDD.html).

2024-05-10 15:25 UTC, aapaecklar commented
Were there any other comments / suggestions for changes apart from the EDD and the unicode?

2024-05-10 17:37 UTC, woutdenolf commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
Yes, you are correct, it is a white beam. Well technically it could be a monochromatic beam that is scanned but I guess this is never done.

But the NXsource energy has nothing to do with this. For example for an X-ray tube, it is the voltage, not the energy of the Cu lines or whatever.

If you want to specify the X-ray energy, you can use an NXbeam at the sample position (NXbeam described the beam at a certain point in space) or NXmonochromator.

2024-05-10 17:38 UTC, woutdenolf commented
> Were there any other comments / suggestions for changes apart from the EDD and the unicode?

No

2024-05-13 08:52 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
Thank you for the information. Following this, would it be better to change "beam_intensity_profile" type="NXcollection" to "beam_intensity_profile" type="NXbeam"?

How would we define the X-ray energy in the group NXbeam for a white beam? Could it beam "final_energy"?

2024-05-13 10:29 UTC, woutdenolf commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
`beam_intensity_profile` is already an NXbeam.

2024-05-13 10:33 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
Yes, you are right. Sorry, I just quickly looked at the version on my computer but obviously it was not the updated one. 

So, last but not least, how would we define the X-ray energy in the group NXbeam for a white beam? Could it be in "final_energy" like a list?

2024-05-13 10:50 UTC, woutdenolf commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
For a monochromatic beam, `incident_energy` is more intuitive (incident on the sample). No idea how to handle white beams.

FYI NXbeam also has NXtransformations so you can define where this beam is identified (you could have more that on NXbeam). Without any transformation you are defining the beam in the origin of the coordinate system. The NXtransformations in NXsample are most likely just rotations so it would be the impact point of the sample.

If you want to use `NXbeam` to define the energy, should we rename `beam_intensity_profile` appropriately, as it is not just to characterize the intensity profile but also the energy?

2024-05-13 10:53 UTC, woutdenolf commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
But lets be practical. In the case of ED-XRD there is no need to say anything about the beam energy. The energy is defined by the detector (MCA).

So I would use `incident_energy` and add to the <doc> that this is only for monochromatic beams.

2024-05-13 11:41 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +			                For X-ray tubes, this would be the excitation voltage. In case of energy dispersive diffraction, the lowest and highest energy should be provided.
Sounds good to me. Thank you.

2024-05-13 13:07 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +                            - if *center_type="momentum-transfer"* then *cUnit* must have the unit \ :math:`\unicode{x212B}^{-1}`
```suggestion
                            - if *center_type="momentum-transfer"* then *cUnit* must have the unit \ :math:`Å`

```

2024-05-13 13:09 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +                            - if *center_type="d-spacing"* then *cUnit* must have the unit \ :math:`\unicode{x212B}`
```suggestion
                            - if *center_type="d-spacing"* then *cUnit* must have the unit \ :math:`Å`

```

2024-05-13 13:09 UTC, aapaecklar commented on contributed_definitions/NXstress.nxdl.xml
> +                            - if *center_type="momentum-transfer"* then *cUnit* must have the unit \ :math:`\unicode{x212B}^{-1}`
```suggestion
                            - if *center_type="momentum-transfer"* then *cUnit* must have the unit \ :math:`Å^{-1}`^{-1}`

```

2024-05-15 12:11 UTC, merged